config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true, uniqueness: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :phone_number, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :rating, presence: true
  validates_numericality_of :rating, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5
  validates :content, presence: true
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create!(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path(@restaurant)
  end

  def destroy
    @restaurant.destroy!
    redirect_to restaurants_path(@restaurant)
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.valid?
      @review.save!
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div class="card">

    <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.button :submit, class: "btn btn-success" %>
    <% end %>

  </div>
    <%= link_to 'Back', restaurants_path(@restaurant), class: "btn btn-primary"  %>
</div>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<div class="container">

  <div class="text-center">

    <h1>A list of all the restaurants</h1>
    <%= link_to 'Add restaurant', new_restaurant_path, class: "btn btn-primary"  %>

    <div class="restaurant-list">

      <% @restaurants.each do |restaurant| %>
      <li><strong>Name:</strong> <%= restaurant.name %></li>
      <li>Category: <%= restaurant.category %></li>
      <li>Address: <%= restaurant.address %></li>
      <li>Phone Number: <%= restaurant.phone_number %></li>
      <%= link_to 'show', restaurant_path(restaurant), class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-primary" %>
      <%= link_to "Delete", restaurant_path(restaurant), class: "btn btn-danger",
      method: :delete,
      data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render "form" %>

app/views/restaurants/show.html.erb
<div class="container">

  <li><strong>Name:</strong> <%= @restaurant.name %></li>
  <li>Category: <%= @restaurant.category %></li>
  <li>Address: <%= @restaurant.address %></li>
  <li>Phone Number: <%= @restaurant.phone_number %></li>


  <h2>Reviews (<%=  @restaurant.reviews.size %>)</h2>
  <% @restaurant.reviews.each do |review| %>
  <li>Rating: <%= review.rating %></li>
  <li>Content: <%= review.content %></li>
  <% end %>

  <%= link_to 'Add review', new_restaurant_review_path(@restaurant), class: "btn btn-primary"  %>



  <%= link_to 'Home', restaurants_path(@restaurant), class: "btn btn-primary"  %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="card">

    <%= simple_form_for(@review, url: restaurant_reviews_path(@restaurant)) do |f| %>
    <%= f.error_notification %>

    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-success" %>
    <% end %>

  </div>
    <%= link_to 'Back', restaurants_path(@restaurant), class: "btn btn-primary"  %>
</div>